# Generated by Django 4.2.1 on 2023-05-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('card_num', models.IntegerField()),
                ('card_pin', models.IntegerField()),
                ('balance', models.FloatField()),
            ],
        ),
    ]
