# Generated by Django 4.2.1 on 2023-05-11 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_useraccount_delete_admin_delete_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='useraccount',
            managers=[
            ],
        ),
    ]
