# Generated by Django 4.2.1 on 2023-05-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='card_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='card_pin',
            field=models.IntegerField(null=True),
        ),
    ]
