# Generated by Django 4.2.1 on 2023-05-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_useraccount_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='civil_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Single'), (2, 'Married'), (3, 'Widowed'), (4, 'Divorced')], null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='card_num',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='card_pin',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
