# Generated by Django 4.2.1 on 2023-05-22 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_usertransactions_usercontacts_transactionticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionticket',
            old_name='receiver',
            new_name='user',
        ),
    ]
