# Generated by Django 4.2.1 on 2023-05-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_useraccount_brand_useraccount_date_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='balance',
        ),
        migrations.AddField(
            model_name='usertransactions',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='usertransactions',
            name='transaction_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertransactions',
            name='transaction_type',
            field=models.CharField(choices=[('PAY', 'Pay'), ('RECEIVE', 'Receive'), ('ADD FUNDS', 'Add funds'), ('TRANSFER TO BANK', 'Transfer to bank')], max_length=20),
        ),
    ]
