# Generated by Django 4.2.1 on 2023-05-30 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0017_remove_useraccount_balance_usertransactions_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertransactions',
            old_name='receiver',
            new_name='user_2',
        ),
        migrations.RemoveField(
            model_name='usertransactions',
            name='sender',
        ),
        migrations.AddField(
            model_name='usertransactions',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usertransactions',
            name='transaction_type',
            field=models.CharField(choices=[('PAY', 'Pay'), ('RECEIVE Payment', 'Receive Payment'), ('ADD FUNDS', 'Add funds'), ('TRANSFER TO BANK', 'Transfer to bank')], max_length=20),
        ),
    ]
