# Generated by Django 4.2.1 on 2023-05-30 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0018_rename_receiver_usertransactions_user_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertransactions',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertransactions',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactionhistory_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
