# Generated by Django 4.2.1 on 2023-05-31 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_usertransactions_transaction_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertransactions',
            name='previous_balance',
            field=models.FloatField(null=True),
        ),
    ]
