# Generated by Django 4.2.1 on 2023-05-31 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_usertransactions_previous_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertransactions',
            name='user_2',
        ),
        migrations.AddField(
            model_name='usertransactions',
            name='sent_to',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
