# Generated by Django 4.2.1 on 2023-06-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_usertransactions_user_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
