# Generated by Django 4.2.1 on 2023-06-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_useraccount_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='card_num',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
